# Generated by Django 4.2.3 on 2023-09-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='street',
        ),
    ]
