# Generated by Django 4.2.3 on 2023-10-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_address_shippingaddress_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
